let hubData=null;const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const root=document.documentElement;const savedTheme=localStorage.getItem("cherryhub-theme");if(savedTheme){root.dataset.theme=savedTheme}
function setThemeButton(){const btn=$("#themeToggle");if(!btn)return;btn.textContent=root.dataset.theme==="light"?"☀":"☾";btn.setAttribute("aria-label",root.dataset.theme==="light"?"Sötét mód":"Világos mód")}
async function loadData(){try{const res=await fetch("data/content.json",{cache:"no-store"});if(!res.ok)throw new Error("content.json nem tölthető be");hubData=await res.json();renderAll()}catch(err){console.error(err);$("#heroLead").textContent="Nem sikerült betölteni a data/content.json fájlt."}}
function renderAll(){setThemeButton();$("#themeToggle").addEventListener("click",()=>{root.dataset.theme=root.dataset.theme==="light"?"dark":"light";localStorage.setItem("cherryhub-theme",root.dataset.theme);setThemeButton()});renderNav();renderHero();renderSocials();renderFlower();renderNews();renderCards();renderWideSections();renderLinks();bindModal();const first=hubData.cards.find(c=>c.id===hubData.petals[0])||hubData.cards[0];if(first)renderFloatingCard(first.id)}
function renderNav(){const nav=$("#mainNav");nav.innerHTML=hubData.nav.map(i=>`<a href="${i.target}">${i.label}</a>`).join("");$(".menu-toggle").addEventListener("click",()=>nav.classList.toggle("open"));nav.addEventListener("click",e=>{if(e.target.matches("a"))nav.classList.remove("open")})}
function renderHero(){$("#heroLead").textContent=hubData.hero.lead;$("#heroActions").innerHTML=hubData.hero.actions.map(a=>`<a class="${a.style}" href="${a.url}" target="${a.url.startsWith("http")?"_blank":"_self"}" rel="noreferrer">${a.label}</a>`).join("")}
function renderSocials(){$("#socialStrip").innerHTML=hubData.socials.map(s=>`<a class="social-link" href="${s.url}" target="_blank" rel="noreferrer"><img src="${s.icon}" alt="" loading="lazy"><span><b>${s.name}</b><span>${s.handle}</span></span></a>`).join("")}
function renderFlower(){const flower=$("#flowerMenu");const petals=hubData.petals.map((id,i)=>{const c=hubData.cards.find(x=>x.id===id);return c?`<button class="petal p${i+1} ${i===0?"active":""}" data-card="${c.id}" aria-label="${c.title}"><span class="icon">${c.icon}</span><strong>${c.title}</strong><small>${c.short}</small></button>`:""}).join("");flower.innerHTML=petals+`<div class="core"><span>Cherry</span><strong>HUB</strong></div>`;$$(".petal",flower).forEach(p=>{const id=p.dataset.card;p.addEventListener("mouseenter",()=>renderFloatingCard(id));p.addEventListener("focus",()=>renderFloatingCard(id));p.addEventListener("click",()=>{$$(".petal",flower).forEach(x=>x.classList.remove("active"));p.classList.add("active");renderFloatingCard(id);document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})})});$(".close-card").addEventListener("click",()=>{const c=$("#floatingCard");c.style.opacity=c.style.opacity==="0"?"1":"0";c.style.pointerEvents=c.style.opacity==="0"?"none":"auto"})}
function renderFloatingCard(id){const d=hubData.cards.find(c=>c.id===id);if(!d)return;const c=$("#floatingCard");$(".card-kicker",c).textContent=`✿ ${d.title}`;$("h2",c).textContent=d.floatingTitle||d.title;$("p",c).textContent=d.floatingText||d.short;$("ul",c).innerHTML=(d.floatingItems||[]).map(([a,b])=>`<li><b>${a}</b><span>${b}</span></li>`).join("");$(".card-link",c).href=`#${d.id}`;c.style.opacity="1";c.style.pointerEvents="auto"}
function renderNews(){$("#newsStrip").innerHTML=hubData.news.map(i=>`<article><b>${i.title}</b><span>${i.text}</span></article>`).join("")}
function renderCards(){$("#cardsGrid").innerHTML=hubData.cards.map(c=>`<article id="${c.id}" class="section-card"><div class="big-icon">${c.icon}</div><h2>${c.title}</h2><p>${c.short}</p><button class="open-modal" type="button" data-open-modal="${c.id}">Több infó</button></article>`).join("")}
function renderWideSections(){$("#wideSections").innerHTML=hubData.wideSections.map(s=>`<article id="${s.id}" class="wide-card"><div class="wide-head"><span>${s.icon}</span><h2>${s.title}</h2></div><p>${s.text}</p>${(s.items||[]).map(i=>`<div class="wide-item"><b>${i.title}</b><p>${i.text}</p><a class="wide-link" href="${i.url}" target="${i.url.startsWith("http")?"_blank":"_self"}" rel="noreferrer">${i.button} →</a></div>`).join("")}${s.note?`<div class="wide-note">${s.note}</div>`:""}</article>`).join("")}
function renderLinks(){$("#links").innerHTML=`<h2>Közösségi linkek</h2><div class="links-row">${hubData.socials.map(s=>`<a href="${s.url}" target="_blank" rel="noreferrer"><img src="${s.icon}" alt="" loading="lazy">${s.name}</a>`).join("")}</div>`}
function bindModal(){document.addEventListener("click",e=>{const o=e.target.closest("[data-open-modal]");if(o)openModal(o.dataset.openModal);if(e.target.closest("[data-close-modal]"))closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()})}
function openModal(id){const d=hubData.cards.find(c=>c.id===id);if(!d)return;$("#modalKicker").textContent=`✿ ${d.title}`;$("#modalTitle").textContent=d.title;$("#modalText").textContent=d.details?.text||d.short;$("#modalContent").innerHTML=(d.details?.blocks||[]).map(b=>`<section class="detail-block"><h3>${b.heading}</h3><ul>${(b.items||[]).map(i=>`<li>${i}</li>`).join("")}</ul></section>`).join("");$("#modalActions").innerHTML=(d.details?.buttons||[]).map(b=>`<a href="${b.url}" target="${b.url.startsWith("http")?"_blank":"_self"}" rel="noreferrer">${b.label}</a>`).join("");const m=$("#infoModal");m.classList.add("show");m.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function closeModal(){const m=$("#infoModal");m.classList.remove("show");m.setAttribute("aria-hidden","true");document.body.style.overflow=""}
loadData();
